project_id = "bmwasmjxptwkrpvqazbf"

[functions.send-team-notification]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-password-reset-email]
verify_jwt = false
